// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcAWy7kVbTJeCNyyeSUY1UHxiyMmIhF_I',
    appId: '1:155305456263:web:8de95b89f0e0f469a1be22',
    messagingSenderId: '155305456263',
    projectId: 'vantan-connect',
    authDomain: 'vantan-connect.firebaseapp.com',
    storageBucket: 'vantan-connect.appspot.com',
    measurementId: 'G-MM2D9TZQZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARx-js85t6qD0hVJz7ubLg9cdDIFGL6JM',
    appId: '1:155305456263:android:ea5c0129f37c41d0a1be22',
    messagingSenderId: '155305456263',
    projectId: 'vantan-connect',
    storageBucket: 'vantan-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoHm7BCmudW-dlPdXUZGur2Xwle4jQkE',
    appId: '1:155305456263:ios:c2d121092d6b1296a1be22',
    messagingSenderId: '155305456263',
    projectId: 'vantan-connect',
    storageBucket: 'vantan-connect.appspot.com',
    iosClientId: '155305456263-rbfrf7gabarg68433ip8ijc753oosa1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vantanConnectForMac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoHm7BCmudW-dlPdXUZGur2Xwle4jQkE',
    appId: '1:155305456263:ios:c2d121092d6b1296a1be22',
    messagingSenderId: '155305456263',
    projectId: 'vantan-connect',
    storageBucket: 'vantan-connect.appspot.com',
    iosClientId: '155305456263-rbfrf7gabarg68433ip8ijc753oosa1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vantanConnectForMac',
  );
}
